package consoclient;

import consoclient.data.Colours;
import consoclient.data.Player;

import java.io.FileWriter;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import consoclient.data.Tile;

/// The GIH, or GameInstanceHandler, deals with all server requests and gameplay related data
public class GIH {
    private static final HttpClient CLIENT = HttpClient.newHttpClient();
    private static String SERVER_URL;
    private static String TOKEN;
    public static Player PLAYER;
    public static Tile CURRENT_TILE;

    // SAVEGAMES STUFF ====================================================================================================

    /// Saves a new game in the games.config file
    /// @param username player's username
    /// @param password player's autogenerated password
    /// @throws Exception may be thrown during encryption process
    public static void createGame(String username, String password) throws Exception {
        String content = username + "=" + password;
        String encrypted = EncryptionHandler.encrypt(content) + "\n";
        FileWriter fw = new FileWriter(Utils.getJarDirectory(App.class) + "/game/games.config");
        fw.append(encrypted);
        fw.close();
    }

    /// Loads all games in the games.config file
    /// @return HashMap containing the username (key) and password (value) for each existing save
    /// @throws Exception may throw exceptions during decryption process
    public static HashMap<String, String> loadGames() throws Exception {
        if (!Files.exists(Paths.get(Utils.getJarDirectory(App.class) + "/game/games.config")))
            return new HashMap<>();

        String encrypted = new String(Files.readAllBytes(Paths.get(Utils.getJarDirectory(App.class) + "/game/games.config"))); // gets all the text in the games.config file
        String[] encryptedArr = encrypted.split("\n");

        HashMap<String, String> saves = new HashMap<>();
        for (String line : encryptedArr) { // saves each save to a KeyValue pair
            String decrypted = EncryptionHandler.decrypt(line);
            String[] parts = decrypted.split("=", 2);
            saves.put(parts[0], parts[1]);
        }
        return saves;
    }

    /// Deletes an existing save from the games.config file
    /// @param username username key of the save to be deleted
    /// @throws Exception may throw exceptions during encryption / decryption process
    public static void deleteGame(String username) throws Exception {
        Map<String, String> saves = loadGames();
        saves.remove(username);

        Files.delete(Paths.get(Utils.getJarDirectory(App.class) + "/game/games.config"));

        FileWriter fw = new FileWriter(Utils.getJarDirectory(App.class) + "/game/games.config");

        for (Map.Entry<String, String> save : saves.entrySet()) {
            String encrypted = EncryptionHandler.encrypt(save.getKey() + "=" + save.getValue()) + "\n";
            fw.append(encrypted);
        }

        fw.close();
    }


    // SERVER STUFF ====================================================================================================

    /// Sets the URL of the game server
    /// @param url the URL value to be applied
    public static void setServerUrl(String url) {
        SERVER_URL = url;
    }

    /// Checks the server at the given URL is active
    /// @return 'true' if server returns code 200
    public static boolean checkStatus() throws Exception {
        HttpRequest request = HttpRequest.newBuilder().uri(URI.create(SERVER_URL + "/status")).GET().build();
        HttpResponse<String> response = CLIENT.send(request, HttpResponse.BodyHandlers.ofString());
        return response.statusCode() == 200;
    }

    /// Logs an existing user into the game
    /// @param username the user's username
    /// @param password the user's autogenerated password
    /// @return Player object containing the player's details
    /// @throws Exception May throw HTTP exceptions
    public static void login(String username, String password) throws Exception {
        String body = String.format("{ \"username\": \"%s\", \"password\": \"%s\" }", username, password); // builds the JSON body of the request

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(SERVER_URL + "/login")) // sets the request URI
                .header("Content-Type", "application/json") // defines the content type as JSON
                .POST(HttpRequest.BodyPublishers.ofString(body)) // set request type (POST)
                .build();

        HttpResponse<String> response = CLIENT.send(request, HttpResponse.BodyHandlers.ofString()); // send request

        if (response.statusCode() != 200) { // ensure the request was a success
            PLAYER = null; // if it wasn't, make sure PLAYER is null so the calling method knows

        } else {
            JsonObject json = JsonParser.parseString(response.body()).getAsJsonObject(); // parse the returned JSON
            TOKEN = json.get("token").getAsString(); // get the JWT token

            PLAYER = new Player(username, json.get("x").getAsInt(), json.get("y").getAsInt());
        }
    }

    /// Registers a new user with the server
    /// @param username new user's username
    /// @param password new user's password
    /// @throws Exception may be thrown by HTTP exceptions
    public static void register(String username, String password) throws Exception {
        String body = String.format("{ \"username\": \"%s\", \"password\": \"%s\" }", username, password); // builds the JSON body of the request

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(SERVER_URL + "/register")) // sets the request URI
                .header("Content-Type", "application/json") // defines the content type as JSON
                .POST(HttpRequest.BodyPublishers.ofString(body)) // set request type (POST)
                .build();

        HttpResponse<String> response = CLIENT.send(request, HttpResponse.BodyHandlers.ofString()); // send request

        if (response.statusCode() == 201) { // ensure the request was a success
            JsonObject json = JsonParser.parseString(response.body()).getAsJsonObject(); // parse the returned JSON
            TOKEN = json.get("token").getAsString(); // get the JWT token
            createGame(username, password);

            PLAYER = new Player(username, json.get("x").getAsInt(), json.get("y").getAsInt());
        } else {
            System.out.println(Colours.RESET + "\nRegistration failed (" + response.statusCode() + "): " + response.body());
            PLAYER = null;
        }
    }

    /// Deletes the currently logged-in user
    /// @throws Exception may throw HTTP exceptions
    public static void delete() throws Exception {
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(SERVER_URL + "/delete"))
                .header("Authorization", "Bearer " + TOKEN)
                .POST(HttpRequest.BodyPublishers.noBody())
                .build();

        HttpResponse<String> response = CLIENT.send(request, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            throw new Exception("Request returned code " + response.statusCode());
        }
    }

    // GAMEPLAY REQUESTS ===============================================================================================
    public static void move(String direction) throws Exception {
        // updates the player's position
        switch (direction) {
            case "north":
                PLAYER.y++;
                break;

            case "south":
                PLAYER.y--;
                break;

            case "east":
                PLAYER.x++;
                break;

            case "west":
                PLAYER.x--;
                break;
        }

        String body = String.format("{ \"x\": \"%s\", \"y\": \"%s\" }", PLAYER.x, PLAYER.y); // builds the JSON body of the request

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(SERVER_URL + "/tile/get")) // sets the request URI
                .header("Authorization", "Bearer " + TOKEN) // defines the content type as JSON
                .POST(HttpRequest.BodyPublishers.ofString(body)) // set request type (POST)
                .build();

        HttpResponse<String> response = CLIENT.send(request, HttpResponse.BodyHandlers.ofString()); // send request

        if (response.statusCode() == 200) { // ensure the request was a success
            JsonObject json = JsonParser.parseString(response.body()).getAsJsonObject(); // parse the returned JSON
            TOKEN = json.get("token").getAsString(); // get the JWT token
            CURRENT_TILE = new Tile(PLAYER.x, PLAYER.y, json.get("biome").getAsString(), json.get("structure").getAsString()); // set the current tile
        } else {
            throw new Exception("Request returned code " + response.statusCode() + "\nMessage: " + response.body());
        }
    }
}
