apiVersion: apps/v1
kind: Deployment
metadata:
  name: consoquest-api
spec:
  replicas: 2
  progressDeadlineSeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: consoquest-api
  template:
    metadata:
      labels:
        app: consoquest-api
    spec:
      containers:
        - name: consoquest-api
          image: consoquest-api:0
          imagePullPolicy: Never
          ports:
            - containerPort: 18080
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password