services:
  postgres:
    image: postgres:alpine
    container_name: postgres-consoquest
    env_file:
      - .env
    ports:
      - "3005:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  react:
    build:
      context: /root/consoquest/web/react-site
      dockerfile: Dockerfile
    container_name: consoquest-react
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  pgdata:
