services:
  postgres:
    image: postgres:alpine
    container_name: postgres-consoquest
    env_file:
      - .env
    ports:
      - "3005:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
